#!/bin/sh

USAGE="plone <vhost> <port> [host] [base]"

if [ "$1" = "help" ]; then
    echo "$USAGE"
    exit 1
fi

VHOST=$1
PORT=$2
HOST=${3:-localhost}
BASE=${4:-""}

if [ -z "$VHOST" -o -z "$PORT" ]; then
    echo $USAGE
    exit 1
fi

echo "Configuring apache with:
  vhost: $VHOST
  port: $PORT
  host: $HOST
  base: $BASE
"

APACHE_BASE=/tmp

if [ ! -w $APACHE_BASE ]; then
    echo "!!! You don't have write permission on $APACHE_BASE"
    echo "!!! Try again as root..."
    echo
    exit 50
fi

if [ -e $APACHE_BASE/sites-available/$VHOST ]; then
    echo "Site config for $VHOST already there"
    read -p "Continue anyway? [y|N]: " PROCEED

    if [ "${PROCEED:-n}" != "y" ]; then
	exit 0
    fi
fi

cat $MOD_BASE/apacheconf.skel | \
    sed -e "s#\${vhost}#$VHOST#g" | \
    sed -e "s#\${host}#$HOST#g" | \
    sed -e "s#\${port}#$PORT#g" | \
    sed -e "s#\${base}#$BASE#g" > \
    $APACHE_BASE/sites-available/$VHOST

read -p "Enable this site? [Y|n]: " ENABLE

if [ "$[ENABLE]" = "n" ]; then
    exit 0
fi

ln -f -s $APACHE_BASE/sites-available/$VHOST $APACHE_BASE/sites-enabled