#!/bin/bash

source $APPIE_BASE/includes

VERSION=$1
PYTHON_VERSION=$2

if [ -z "$VERSION" -o -z "$PYTHON_VERSION" ]; then
  echo "Usage: plone:sys_install <version> <python version>"
  exit 1;
fi

# Check permissions
#
if [ `isAppAdmin` != "true" ]; then
    echo "Looks like you're not an app admin. Too bad..."
    exit 50
fi

if [ ${#PYTHON_VERSION} -ne 3 ]; then
    echo "$PYTHON_VERSION is not a major version!"
    echo "Major versions are of the form X.Y"
    exit 1
fi

TGT=$PLONE_BASE/py-$PYTHON_VERSION

if [ ! -d $TGT ]; then
    mkdir -p $TGT
    chgrp appuser $TGT
    chmod g+w $TGT
fi

PKG=`$WGET -O - $PLONE_SOURCES/plone/releases/$VERSION | grep "Plone-$VERSION.tar.gz" | head -1 | awk -F '"' '{print $2}'` 


wget -O - $PKG | tar -C $TGT -xz
chmod -R g+w $TGT

echo "Done"
echo ""
